### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SHGoldfarb** [trabajosproyecta/cubicator3000#2]
Comentar o documentar el codigo para que se entienda.

**Comment by ironcadiz** [comment]
Dividiría esta issue en varias secciones para poder repartirlo en las tarjetas.

**Comment by SHGoldfarb** [comment]
Quizas.. por modulo?

**Comment by SHGoldfarb** [comment]
Tambien pasar las variables y comentarios existentes que estan en español a inglés

**Comment by ironcadiz** [comment]
Voy a dividir esto en varias issues
